### ISSUE TITLE
Run long time in runPhyML.py

### ISSUE THREAD

**Issue by jiyunli** [philarevalo/PopCOGenT#1]
Dear sir,
It good job in gene-flow and I want to explore the gene-flow in different host. So ran the code as your pipelines using your example in test directory. Then it still running and no error report in tree days later when run the phybreak3.MSAsubset_runPhyML.py. Hope your help.
Best regard,
Yun

**Comment by philarevalo** [comment]
Hi Yun,

To clarify, are you running the scripts on the 12 genomes in the test dataset? If you are running it on your own data, how many genomes are you trying to analyze?

Thanks,
Phil

**Comment by jiyunli** [comment]
Yes, I meet the problem when run the 12 genomes in the test dataset. I haven't run my data and my data is about ~60 isolates to run. I will run my data.

**Comment by davevanins** [comment]
Hi Yun,

Can you tell me if the file containing all of the location information for each tree it will make (ends with ".treeloc.txt" in "align/phy_split/") or the phylip formatted tree file (ends with ".phy" also in "align/phy_split/") have been created yet?

Thanks,
Dave

**Comment by jiyunli** [comment]
@philarevalo HI Phil,
 I meet same problem when running it on my data and I think the step is meet some error：phyml -i /disk1/cau/cvmlll/pop/PopCOGenT-master/src/core_gene_sweeps/align/phy_split/sulpho.phy -n 757 -q -m JC69 -f e -c 2 -a 0.022

@davevanins HI Dave.
The ".treeloc.txt" and ".phy" have been created. the detail is following:
[cvmlll@mu01 phy_split]$ pwd
/disk1/cau/cvmlll/pop/PopCOGenT-master/src/core_gene_sweeps/align/phy_split
[cvmlll@mu01 phy_split]$ ll
total 48624
-rw-r--r-- 1 cvmlll cau 49771956 Sep 22 22:07 sulpho.phy
-rw-r--r-- 1 cvmlll cau        0 Sep 22 22:07 sulpho.phy_phyml_stats.txt
-rw-r--r-- 1 cvmlll cau      151 Sep 22 22:08 sulpho.phy_phyml_stat.txt
-rw-r--r-- 1 cvmlll cau        0 Sep 22 22:07 sulpho.phy_phyml_tree.txt
-rw-r--r-- 1 cvmlll cau    12091 Sep 22 22:07 sulpho.treeloc.txt

**Comment by davevanins** [comment]
There is definitely something unusual happening, sorry you're having to deal with this. 

When I run the scripts myself, this step takes approximately 12 hours to generate 4212 trees from that set of genomes. The command you copied suggests it is only trying to make 757. Can you send me your "phybreak_parameters.txt" and "sulpho.treeloc.txt" files?

**Comment by jiyunli** [comment]
Thank your help.
I have dealt with the problem, it is problem in phyml because I install phyml used bioconda. It's go well when using another installation method.

Hmmm! The new trouble is arrived. What should I do ? 
When I run "python phybreak7.find_sweeps.py", the feedback as following:
Traceback (most recent call last):
  File "phybreak7.find_sweeps.py", line 220, in <module>
    concat_pop = find_sweeps(phybreak_result, div_df, p0, 0.95, focus_population, pop_list)
  File "phybreak7.find_sweeps.py", line 110, in find_sweeps
    concat = concatenate_windows(trees_passing_phy_criteria, length_cutoff=500)
  File "phybreak7.find_sweeps.py", line 44, in concatenate_windows
    final_df['Midpoint'] = final_df.Start + ((final_df.End - final_df.Start) // 2)
  File "/disk1/cau/cvmlll/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Start'

**Comment by philarevalo** [comment]
@jiyunli I will try to reproduce this error and see if I can track it down. Can you send me the first 10 lines of the following two files? 

`phy_split/phybreak_result_sulpho.txt`
`phy_split/sulpho.treeloc.txt`

Thanks,
Phil

**Comment by jiyunli** [comment]
@philarevalo I only find align/phybreak_result_0.0.txt and align/phy_split/sulpho.treeloc.txt, and have no "phybreak_result_sulpho.txt" file.

sulpho.treeloc.txt:
1	97	48742
2	148	51340
3	205	52341
4	367	52553
5	450	52626
6	461	52713
7	467	53769
8	1044	54670
9	1614	54913
10	1623	54944

phybreak_result_0.0.txt:
mid_point_of_window	tree_no	monophy	other	other_percentile	focus	focus_percentile	mono_phy_low_diversity
24419.5	1	1	0.05026052601694937	0.8684668989547039	0.18640220569011004	0.47473867595818814	0
25744.0	2	1	0.02527570912581394	0.6803135888501742	0.2756561678809639	0.7369337979094077	0
26273.0	3	1	0.0513426859522117	0.8719512195121951	0.18843337070788505	0.49390243902439024	0
26460.0	4	1	0.02579996771489125	0.6881533101045296	0.2790193658579767	0.7430313588850174	0
26538.0	5	1	0.051624745177206645	0.8736933797909407	0.19223668783084502	0.5078397212543554	0
26587.0	6	1	0.02586251512764649	0.6916376306620209	0.2845326859964962	0.7473867595818815	0
27118.0	7	1	0.05035844137417307	0.8702090592334495	0.19251263678768424	0.5113240418118467	0
27857.0	8	1	0.025197409406431767	0.6785714285714286	0.28461138434178235	0.7482578397212544	0
28263.5	9	1	0.04905784706142154	0.8623693379790941	0.19266826999887104	0.5121951219512195	0
28283.5	10	1	0.024515597915664992	0.6672473867595818	0.2845060526974114	0.7456445993031359	0

At the before, sulpho.phy_phyml_tree.txt have 8402 entries(trees) and  sulpho.phy_phyml_tree.txt have 4201 lines. so I del the 4201 entries in sulpho.phy_phyml_tree.txt, and then the fourth step "phybreak4.retrieveLikelihood.py" went through successfully.

**Comment by philarevalo** [comment]
Thanks Yun, I'll have time to take a look at this within the next couple of days. Sorry for the delay!

**Comment by philarevalo** [comment]
Hi Yun,

I think I've been able to fix the issue. There were bugs involving the expected location and format of output files. I've made some other small changes as well, so this will require updating your repo and re-running scripts 4, 5, 6, and 7. I've also changed the format of `percentile_threhold` in the configuration file, so if you pull the repo, you will have to make sure that all the paths in `phybreak_parameters.txt` are correct for your machine.

Let us know if you run into any problems.

Best,
Phil

**Comment by jiyunli** [comment]
Thanks Phil. I can go through the "phybreak7.find_sweeps.py" according to you fix script. 

There meet another problem,
sulpho.phy_phyml_tree.txt have 8404 entries(trees) and sulpho.phy_phyml_tree.txt have 4202 lines. so I del the 4202 entries in sulpho.phy_phyml_tree.txt, and then the fourth step "phybreak4.retrieveLikelihood.py" went through successfully. there are feedback:
[cvmlll@mu01 core_gene_sweeps]$ Traceback (most recent call last):
  File "phybreak4.retrieveLikelihood.py", line 142, in <module>
    ML_dict[subseq][str(tree_no)] += tree
KeyError: '4203'

**Comment by philarevalo** [comment]
Hi Yun,

I was not able to recreate this error. Can you tell me what version of phyml you are using? Does `sulpho.phy_phyml_tree.txt` appear to have 4202 trees followed by an exact copy of the same 4202 trees?

**Comment by jiyunli** [comment]
PhyML is PhyML 3.3.20190909. 
Sorry, I made a mistake. "sulpho.phy_phyml_tree.txt" (8404 entries) always twice as much as "sulpho.treeloc.txt"(4202 trees)，and not an exact copy.

**Comment by philarevalo** [comment]
There's a chance that this might be a versioning issue--this code was tested with phyml version 3.1, so I will try it with version 3.3 and see if that reproduces the error. It does not appear that version 3.1 is easily available anymore.

**Comment by philarevalo** [comment]
Can you also run the following command on the `sulpho.phy` file and tell me what it outputs? It should be in `align/phy_split/`

`grep "^ 12" sulfo.phy | wc -l`

**Comment by jiyunli** [comment]
I run it and print "4202"

**Comment by jiyunli** [comment]
I download and install PhyML-3.1 from http://www.atgc-montpellier.fr/phyml/versions.php. the seven command is work well. just had a warnings in run "phybreak4.retrieveLikelihood.py" as following: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by philarevalo** [comment]
Great, thank you for finding that! I was looking on their github which is why I couldn't find that. @davevanins can confirm this, but the warnings for phybreak4 are normal to our knowledge and do not affect output.

**Comment by jiyunli** [comment]
Thank you for this issue.

**Comment by davevanins** [comment]
That's right, the message "There were 50 or more warnings (use warnings() to see the first 50)" isn't a bug. Expected behavior
