### ISSUE TITLE
PopCOGenT, cannot find Bio

### ISSUE THREAD

**Issue by joneson** [philarevalo/PopCOGenT#11]
Hello, I have been trying to get PopCOGenT running with the test data. I have not been able to get past this error.Is this the right place to ask for help?

(PopCOGenT) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ bash PopCOGenT.sh
Traceback (most recent call last):
  File "get_alignment_and_length_bias.py", line 5, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
Traceback (most recent call last):
  File "cluster.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'

After the following I can see that biopython is in the PopCOGenT env.
conda list -n PopCOGenT

I installed the PopCOGenT environment in the following manner:
conda config --set restore_free_channel true
conda env create -f PopCOGenT.yml
conda install --name PopCOGenT mugsy=1.2.3 muscle=3.8.31
(I was not able to install phyml, mmseqs2, or infomap this way and have yet to install them).
And I have inserted the miniconda3 pathway as the mugsy installation and mugsyenv.sh

Thank-you,
Suzanne

**Comment by philarevalo** [comment]
Hello!

Can you run the following commands and paste the output here?

conda list -n PopCOGenT

**Comment by joneson** [comment]
Yes, thank-you for your reply.

(PopCOGenT) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ conda list -n
PopCOGenT
# packages in environment at /home/tate/miniconda3/envs/PopCOGenT:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_r-mutex                  1.0.0               anacondar_1
asn1crypto                1.3.0                    py36_0
bcrypt                    3.1.7            py36h7b6447c_0
biopython                 1.68                np111py36_0
blas                      2.11                   openblas    conda-forge
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.14.8                        0
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.14.0           py36h2e261b9_0
chardet                   3.0.4                 py36_1003
cryptography              2.8              py36h1ba5d50_0
curl                      7.68.0               hbc83047_0
decorator                 4.4.1                      py_0
docutils                  0.16                     py36_0
dropbox                   9.4.0                    py36_0
filechunkio               1.6                      py36_0    bioconda
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
ftputil                   3.2                      py36_0    bioconda
glib                      2.50.2                        1
gsl                       2.4                  h14c3975_4
harfbuzz                  0.9.39                        2
icu                       54.1                          0
idna                      2.8                      py36_0
jbig                      2.1                  hdba287a_0
joblib                    0.9.4                    py36_0
jpeg                      8d                            2
krb5                      1.17.1               h173b8e3_0
ld_impl_linux-64          2.33.1               h53a641e_7
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.68.0               h20c2e04_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran               3.0.0                         1
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.14                          0
liblapack                 3.8.0               11_openblas    conda-forge
liblapacke                3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h5a2b251_2
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.16               h1bed415_0
libssh2                   1.8.2                h1ba5d50_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.6                         2
libxml2                   2.9.9                hea5a465_1
mugsy                     1.2.3                         3    bioconda
muscle                    3.8.31                        0    bioconda
ncurses                   6.1                  he6710b0_1
networkx                  1.11                     py36_1
numpy                     1.11.3          py36h99e49ec_12
numpy-base                1.11.3          py36h2f8d375_12
openblas                  0.2.19                        0
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    0.19.2              np111py36_1
pango                     1.40.3                        1
paramiko                  2.6.0                    py36_0
patsy                     0.5.1                    py36_0
pcre                      8.39                          1
perl                      5.26.2            h516909a_1006    conda-forge
pip                       20.0.2                   py36_1
pixman                    0.34.0               hceecf20_3
pycparser                 2.19                     py36_0
pynacl                    1.3.0            py36h7b6447c_0
pyopenssl                 19.1.0                   py36_0
pysftp                    0.2.9                    py36_0    bioconda
pysocks                   1.7.1                    py36_0
python                    3.6.10               h0371630_0
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pyyaml                    5.3              py36h7b6447c_0
r-assertthat              0.1                    r3.3.2_4
r-base                    3.3.2                         0
r-bh                      1.62.0_1               r3.3.2_0
r-broom                   0.4.1                  r3.3.2_0
r-colorspace              1.3_1                  r3.3.2_0
r-curl                    2.3                    r3.3.2_0
r-dbi                     0.5_1                  r3.3.2_0
r-dichromat               2.0_0                  r3.3.2_2
r-digest                  0.6.10                 r3.3.2_0
r-dplyr                   0.5.0                  r3.3.2_0
r-forcats                 0.1.1                  r3.3.2_0
r-foreign                 0.8_67                 r3.3.2_0
r-ggplot2                 2.2.0                  r3.3.2_0
r-gtable                  0.2.0                  r3.3.2_0
r-haven                   1.0.0                  r3.3.2_0
r-hms                     0.3                    r3.3.2_0
r-httr                    1.2.1                  r3.3.2_0
r-jsonlite                1.1                    r3.3.2_0
r-labeling                0.3                    r3.3.2_2
r-lattice                 0.20_34                r3.3.2_0
r-lazyeval                0.2.0                  r3.3.2_0
r-lubridate               1.6.0                  r3.3.2_0
r-magrittr                1.5                    r3.3.2_2
r-mass                    7.3_45                 r3.3.2_0
r-mime                    0.5                    r3.3.2_0
r-mnormt                  1.5_5                  r3.3.2_0
r-modelr                  0.1.0                  r3.3.2_0
r-munsell                 0.4.3                  r3.3.2_0
r-nlme                    3.1_128                r3.3.2_0
r-openssl                 0.9.5                  r3.3.2_0
r-plyr                    1.8.4                  r3.3.2_0
r-psych                   1.6.9                  r3.3.2_0
r-purrr                   0.2.2                  r3.3.2_0
r-r6                      2.2.0                  r3.3.2_0
r-rcolorbrewer            1.1_2                  r3.3.2_3
r-rcpp                    0.12.8                 r3.3.2_0
r-readr                   1.0.0                  r3.3.2_0
r-readxl                  0.1.1                  r3.3.2_0
r-reshape2                1.4.2                  r3.3.2_0
r-rvest                   0.3.2                  r3.3.2_0
r-scales                  0.4.1                  r3.3.2_0
r-selectr                 0.3_0                  r3.3.2_0
r-stringi                 1.1.2                  r3.3.2_0
r-stringr                 1.1.0                  r3.3.2_0
r-tibble                  1.2                    r3.3.2_0
r-tidyr                   0.6.0                  r3.3.2_0
r-tidyverse               1.0.0                  r3.3.2_0
r-xml2                    1.0.0                  r3.3.2_0
readline                  7.0                  h7b6447c_5
requests                  2.22.0                   py36_1
rpy2                      2.8.5              py36r3.3.2_2
scipy                     0.18.1          np111py36_nomkl_1
setuptools                45.2.0                   py36_0
singledispatch            3.4.0.3                  py36_0
six                       1.14.0                   py36_0
snakemake                 3.11.2                   py36_1    bioconda
sqlite                    3.31.1               h7b6447c_0
statsmodels               0.8.0            py36h8533d0b_0
tk                        8.6.8                hbc83047_0
urllib3                   1.25.8                   py36_0
wheel                     0.34.2                   py36_0
wrapt                     1.11.2           py36h7b6447c_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3

**Comment by philarevalo** [comment]
Two things:  Can you try running the following series of commands directly from the shell? I've seen one other instance where, for some reason, conda doesn't properly work from a shell script.

```
source ./config.sh
source activate PopCOGenT
source ${mugsy_env}
python get_alignment_and_length_bias.py --genome_dir ${genome_dir} --genome_ext ${genome_ext} --alignment_dir ${alignment_dir} --mugsy_path ${mugsy_path} --mugsy_env ${mugsy_env} --base_name ${base_name} --final_output_dir ${final_output_dir} --num_threads ${num_threads} ${keep_alignments}
```

Also, it might be helpful to know exactly what version of linux you're running, so could you share the output of the following command?

```
cat /etc/os-release
```

**Comment by joneson** [comment]
Thank-you very much for your help.

Output from cat
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="
https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

I also did this
(base) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ source ./config.sh
(base) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ conda activate
PopCOGenT
(PopCOGenT) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ source
${mugsy_env}
(PopCOGenT) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ python
get_alignment_and_length_bias.py --genome_dir ${genome_dir} --genome_ext
${genome_ext} --alignment_dir ${alignment_dir} --mugsy_path ${mugsy_path}
--mugsy_env ${mugsy_env} --base_name ${base_name} --final_output_dir
${final_output_dir} --num_threads ${num_threads} ${keep_alignments}
Traceback (most recent call last):
  File "get_alignment_and_length_bias.py", line 5, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by joneson** [comment]
My deepest apologies. I have made a couple of additional changes and now
PopCOGenT has gotten further.

My first error: even though I had properly entered the mugsy_path in
config.sh file, my mugsyenv.sh file mistakenly pointed to the miniconda3
installation of mugsy instead of the miniconda3/envs/PopCOGenT/bin/
directory. I had done this earlier when having difficulty installing mugsy
within the PopCOGenT environment.

The second error came from not including an absolute path to proc/ . In the
many incarnations of trying to make it work in my hands, I had written it
./proc/ which doesn't work.

As a result I have successfully run PopCOGenT.sh the furthest it has ever
gone. The error in the most recent run is
FileNotFoundError: [Errno 2] No such file or directory:
'infomap_out/test_0.000355362.txt_0.tree'
I assume this is because my path to infomap points to the miniconda3
installation, instead of infomap being installed in the PopCOGenT
environment. I haven't been able to install infomap using
conda install --name PopCOGenT infomap=0.18.3
but will keep searching.

Again, I apologize for my oversight, and I appreciate your help.

Suzanne

**Comment by joneson** [comment]
I unfortunately cannot get past this next error. Do you think it could be a result of using the wrong infomap version? I have been unable to find infomap=0.18.3 for downloading. Can you point me to the location?

I have installed Infomap version 1.0.0-beta.58 in the PopCOGenT env using pip. Infomap appears to be working, but the xxx..txt_0.tree is not written to infomap_out/.

(PopCOGenT) tate@Zareason:~/PopCOGenT-master/src/PopCOGenT$ bash PopCOGenT.sh
         Strain 1       Strain 2
4   M1613_contigs  M1627_contigs
14  M1646_contigs  M1627_contigs
62  M1612_contigs  M1622_contigs
=======================================================
  Infomap v1.0.0-beta.58 starts at [2020-02-15 09:48:12]
  -> Input network: infomap_out/test_0.000355362.txt_0.net
  -> Output path:   infomap_out/
  -> Configuration: input-format = pajek
=======================================================
Parsing undirected pajek network from file 'infomap_out/test_0.000355362.txt_0.net'... 
  Parsing vertices...
  -> 9 physical nodes added
  Parsing links...
  -> 36 links
Done!
-------------------------------------
  -> 9 nodes
  -> 36 links with total weight 33658.9483
  -> Ordinary network input, using the Map Equation for first order network flows
Calculating global network flow using flow model 'undirected'... 
  -> Using undirected links.
  => Sum node flow: 1, sum link flow: 1
Build internal network with 9 nodes and 36 links...
Calculating one-level codelength... done!
 -> One-level codelength: 3.03639856

================================================
Trial 1/1 starting at [2020-02-15 09:48:12]
================================================
Two-level compression: 9.3% 0% 
Partitioned to codelength 0.0855549394 + 2.66709895 + 0 = 2.752653887 in 2 modules.
Super-level compression: to codelength 2.752653887 in 2 top modules.

Recursive sub-structure compression: 0% . Found 2 levels with codelength 2.752653887

=> Trial 1/1 finished in 0.00044s with codelength 2.8


================================================
Summary after 1 trial
================================================
Best end modular solution in 2 levels:
Per level number of modules:         [          2,           0] (sum: 2)
Per level number of leaf nodes:      [          0,           9] (sum: 9)
Per level average child degree:      [          2,         4.5] (average: 4.04545)
Per level codelength for modules:    [0.085554939, 0.000000000] (sum: 0.085554939)
Per level codelength for leaf nodes: [0.000000000, 2.667098947] (sum: 2.667098947)
Per level codelength total:          [0.085554939, 2.667098947] (sum: 2.752653887)

===================================================
  Infomap ends at [2020-02-15 09:48:12]
  (Elapsed time: 0.00083s)
===================================================
Traceback (most recent call last):
  File "cluster.py", line 315, in <module>
    main()
  File "cluster.py", line 116, in main
    for line in open(infomap_outfile, 'r'):
FileNotFoundError: [Errno 2] No such file or directory: 'infomap_out/test_0.000355362.txt_0.tree'

**Comment by philarevalo** [comment]
Can you paste your config.sh file here? I do not think this is an infomap version problem, but a problem with filepaths.

**Comment by joneson** [comment]
Thanks! The config.sh is below. I have also set within the mugsyenv.sh
export MUGSY_INSTALL=/home/tate/miniconda3/envs/PopCOGenT/bin/

# Base name for final output files ust a prefix to identify your outputs.
base_name='test'

# Output directory for the final output files.
# This will create the directory if it does not already exist.
final_output_dir=/home/tate/PopCOGenT-master/src/PopCOGenT/output/
#final_output_dir=./output/
mkdir -p ${final_output_dir}

# Path to mugsy and mugsyenv.sh. Please provide absolute path.
mugsy_path=/home/tate/miniconda3/envs/PopCOGenT/bin/mugsy
mugsy_env=/home/tate/miniconda3/envs/PopCOGenT/bin/mugsyenv.sh

# Path to infomap executable. Please provide absolute path.
infomap_path=/home/tate/miniconda3/envs/PopCOGenT/bin/infomap

# Path to genome files.
genome_dir=../../test/

# Genome file filename extension.
genome_ext=.fasta

# Are you running on a single machine? Please specify the number of threads
to run.
# This can, at maximum, be the number of logical cores your machine has.
num_threads=2

# Whether to keep alignments after length bias is calculated.
# Alignment files can be 10MB each and thus a run on 100 genomes can take
up on the order of 50 GB of space if alignment files are not discarded.
# If you want to keep alignments, set to --keep_alignments. Otherwise leave
as ''.
keep_alignments=--keep_alignments

# Directory for output alignments. Must provide absolute path.
alignment_dir=/home/tate/PopCOGenT-master/src/PopCOGenT/proc/
#alignment_dir=$(pwd)/proc/
mkdir -p ${alignment_dir}

# Are your genomes single-cell genomes? If so, this should equal
--single_cell. Otherwise leave as ''.
single_cell=''

# Are you using a slurm environment? Then this should equal --slurm,
otherwise, leave as empty quotes.
slurm_str=''

# If using slurm, please specify the output directory for the runscripts
and source scripts. Absolute paths required.
script_dir=''
source_path=''

**Comment by philarevalo** [comment]
Aha! I think you actually are correct and this has to do with the version of Infomap. I will have time to push the exact version we used to the repo tonight. It is unfortunate that it's seemingly no longer available! We'll mark this as an issue to fix more permanently (i.e., having this work with the most recent supported version).

**Comment by joneson** [comment]
I appreciate all of your help.

**Comment by philarevalo** [comment]
I've added the version of Infomap that we used to the repo. Give it a try and let me know if it works!

**Comment by joneson** [comment]
Thanks. It works!

I downloaded your version of Infomap and installed it in the
miniconda3/envs/PopCOGent/bin/. I don't know if this was important or if I
could've just directed it to the Infomap directory outside of the envs/.

In the end, the test data recovers one cluster with two nodes (1,4,8,7 and
6,5,9) and one edge? My Infomap.png is attached.

Thankyou very much for all of your help!

**Comment by philarevalo** [comment]
I can't seem to see the picture you're referring to. Can you paste the contents of the `*.cluster.tab.txt` file here?

**Comment by joneson** [comment]
Right, thank-you. Here is the output:

Strain  Cluster_ID      Main_cluster    Sub_cluster     Clonal_complex
M1643_contigs   0.0     0       0       M1643_contigs
M1613_contigs   0.0     0       0
M1613_contigs,M1627_contigs,M1646_contigs
M1627_contigs   0.0     0       0
M1613_contigs,M1627_contigs,M1646_contigs
M1646_contigs   0.0     0       0
M1613_contigs,M1627_contigs,M1646_contigs
M1623_contigs   0.0     0       0       M1623_contigs
M1630_contigs   0.0     0       0       M1630_contigs
M1647_contigs   0.0     0       0       M1647_contigs
M1612_contigs   0.0     0       0       M1612_contigs,M1622_contigs
M1622_contigs   0.0     0       0       M1612_contigs,M1622_contigs
M164_contigs    0.1     0       1       M164_contigs
M1640_contigs   0.1     0       1       M1640_contigs
M162_contigs    0.1     0       1       M162_contigs

**Comment by philarevalo** [comment]
Yes that looks right! This means that PopCOGenT identified two populations (0.1 and 0.0) which is the expected result.
