### ISSUE TITLE
conda env create error: joblib=0.9.4 package not found

### ISSUE THREAD

**Issue by k6logc** [philarevalo/PopCOGenT#5]
Hello!

Would love to try PopCOGenT but ran into the error below getting started. I tried adding channels with the indicated joblib version to the yml but that didn't do the trick. Any suggestions? Thank you very much!

[k6logc@eofe7 PopCOGenT]$ conda env create -f PopCOGenT.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - joblib=0.9.4

**Comment by philarevalo** [comment]
Hi!

I'm aware of some issues that have popped up regarding versioning in the conda environment installation and I'm currently working on a fix. Sorry about that!

**Comment by philarevalo** [comment]
Could you try changing the following line in the PopCOGenT.yml file from:

`joblib=0.9.4`

to 

`joblib=0.9.4=py36_0`

If that does not work, let us know.

**Comment by k6logc** [comment]
Thank you for the super fast reply! 

Just tried that and still get an error - below.
And though the error report has "joblib==0.9.4=py36_0",  in the yml I do have "joblib=0.9.4=py36_0"

[k6logc@eofe7 PopCOGenT]$ conda env create -f PopCOGenT.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - joblib==0.9.4=py36_0

**Comment by k6logc** [comment]
Hello!
I discovered that someone else had joblib=0.9.4 through channel "free". I ran command below for my base conda (based on info in link below that) and the "conda env create -f PopCOGenT.yml" command works now with the original yml as provided.

conda config --set restore_free_channel true
https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/free-channel.html

**Comment by vinisalazar** [comment]
Hi, I ran through this same error. I created an environment from scratch with all the latest versions of each dependency. Am in the processing of testing it and will report the results.

**Comment by philarevalo** [comment]
@k6logc This makes sense. When we developed this pipeline, we were using an earlier version of conda than 4.7. We'll do more extensive testing on the latest conda version in the next couple of days. 

@vinisalazar Let me know what you find. In my experience there were some issues different versions of networkx and statsmodels.

**Comment by vinisalazar** [comment]
@philarevalo the main problems I'm having are with the `cluster.py` file, which is compatible with NetworkX 1.11 but raises errors with NetworkX 2.x

Seeing as the dependencies are a bit outdated, I do believe a refactoring might be worth it. I will work on this in the next few days and might create a separate issue.

**Comment by philarevalo** [comment]
@vinisalazar thanks. Before I pull in code that works with networkx2, I am planning to create a release that replicates the key results from the paper using the same versions we used prior to publication. So if you do make a fix, I may wait a bit before pulling in the branch, just FYI.

**Comment by vinisalazar** [comment]
@philarevalo if that is the case I'll see about the other dependencies and leave NX v1.11 for now. I'll stay tuned to the updates.
