### ISSUE TITLE
License and contributing

### ISSUE THREAD

**Issue by vinisalazar** [philarevalo/PopCOGenT#6]
Hi,

thank you for providing this package. I am excited to use it.

Do you intend in providing a license, and perhaps a contributing guide?

Kind regards,

V

**Comment by philarevalo** [comment]
We totally neglected to add a license, so I will definitely do that. As for a contributing guide, it is not something we have thought through extensively. I've been talking with my co-authors about what our plans are for supporting and improving the pipeline and I will definitely keep a contributing guide in mind.

**Comment by vinisalazar** [comment]
That is great. I have already forked the project and would be happy to contribute.
